Chat Page Beginneth
LarrySchultheis/rockr-ui pull request #18
Opened 2023-07-16 20:39 UTC by LarrySchultheis

Added basic chat page. Currently non-functional but match population works. Added cypress test for message page. Draft to link to in doc.

2023-07-23 20:16 UTC, LarrySchultheis commented
Will fix outstanding compiler issue next week. Just going to overwrite merge checks

2023-07-23 21:08 UTC, squaill requested changes

2023-07-23 21:08 UTC, squaill commented on src/App.js
> +      fetch(`http://localhost:5000/get_user_role?id=${user.sub}&email=${user.email}`, requestOptions)
we should touch base about this tomorrow too. I'm confused about the reason for these changes

2023-07-23 21:08 UTC, squaill commented on src/components/ChatService/ChatManager.js
> +        console.log('sending message');
are these console logs an oops?

2023-07-23 21:08 UTC, squaill commented on src/components/ChatService/ChatPage.js
> +      axiosInstance.get(`/matches?email=${props.user.email}`).then(response => {
🎉🎉🎉🎉🎉🎉 thx for using axios

2023-07-24 01:32 UTC, LarrySchultheis commented
I think its good enough

2023-07-24 01:32 UTC, merged